version: '3'
services:
#PHP Service
app:
build:
context: .
container_name: app
environment:
DB_HOST: db
DB_PASSWORD: your_mysql_root_password
DB_USERNAME: root
depends_on:
- db
ports:
- "8080:80"
volumes:
- ./:/var/www/html


